name: Build Clojure From Source

on:
  workflow_call:
    inputs:
      javaVersion:
        description: "Java Version"
        type: string
        required: true
      repository:
        description: "Repository name with owner."
        type: string
        required: true
      ref:
        description: "The branch, tag or SHA to checkout"
        type: string
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.javaVersion }}

      - name: Checkout Clojure Source Code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          path: 'clojure-source'

      - name: Build Clojure from Source
        run: |
          cd clojure-source
          mvn install

