name: Test against datomic

on:
  workflow_dispatch:
    inputs:
      javaVersion:
        description: "Java Version"
        required: true
        default: '11'
      repository:
        description: "Repository name with owner."
        required: true
        default: 'clojure/clojure'
      ref:
        description: "The branch, tag or SHA to checkout"
        required: true
        default: 'master'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.javaVersion }}

      - name: Checkout Clojure Source Code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          path: 'clojure-source'

      - name: Build Clojure from Source
        run: |
          cd clojure-source
          mvn install

      - name: Create dev-local.edn
        run: |
          mkdir $HOME/.datomic
          pwd
          ls -la
          cd $HOME/.datomic
          echo '{:storage-dir "/home/runner"}' > dev-local.edn

      - name: Checkout Integration Test Source Code
        uses: actions/checkout@v4
        with:
          repository: JarrodCTaylor/clojure-integration-tests
          ref: 'main'
          path: 'test-source'

      - name: Install CLI
        run: |
          curl -L -O https://github.com/clojure/brew-install/releases/latest/download/posix-install.sh
          chmod +x posix-install.sh
          sudo ./posix-install.sh
          clojure

      - name: Determine latest snapshot version
        run: |
          pwd
          ls -la
          chmod +x ./test-source/scripts/find-latest-snapshot.sh
          ./test-source/scripts/find-latest-snapshot.sh

      - name: Run Tests
        run: |
          pwd
          ls -la
          cd test-source
          clojure -Srepro -Sdeps '{:deps {org.clojure/clojure {:mvn/version $LATEST_SNAPSHOT}}}' -M:test datomic
