name: Test against datomic

on:
  workflow_dispatch:
    inputs:
      javaVersion:
        description: "Java Version"
        required: true
        default: '11'
      repository:
        description: "Repository name with owner."
        required: true
        default: 'clojure/clojure'
      ref:
        description: "The branch, tag or SHA to checkout"
        required: true
        default: 'master'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.javaVersion }}

      - name: Checkout Clojure Source Code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          path: 'clojure-source'

      - name: Build Clojure from Source
        run: |
          cd clojure-source
          mvn install

      - name: Create dev-local.edn
        run: |
          mkdir $HOME/.datomic
          cd $HOME/.datomic
          echo '{:storage-dir "/home/runner"}' > dev-local.edn
          cd $HOME

      - name: Checkout Integration Test Source Code
        uses: actions/checkout@v4
        with:
          repository: JarrodCTaylor/clojure-integration-tests
          ref: 'main'
          path: 'test-source'

      - name: Run Tests
        run: |
          cd test-source
          clojure -Srepro -Sdeps '{:deps {org.clojure/clojure {:mvn/version "1.12.0-master-SNAPSHOT"}}}' -M:test datomic
